export const ALERT = "ALERT";
export const REFECTH_CHATS = "REFECTH_CHATS";

export const NEW_ATTACHMENTS = "NEW_ATTACHMENTS";
export const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";
export const NEW_REQUEST = "NEW_REQUEST";
export const NEW_MESSAGE = "NEW_MESSAGE";
export const STRAT_TYPING="STRAT_TYPING"
export const STOP_TYPING="STOP_TYPING"
export const CHAT_JOINED="CHAT_JOINED"
export const CHAT_LEAVED="CHAT_LEAVED"
export const ONLINE_USERS="ONLINE_USERS"